### PR TITLE
QOL Improvements

### PR DESCRIPTION
**Pull request by wilsam239**
Implemented a method of viewing titles that have been updated, installed, or excluded.

- Use of a custom Title struct has been implemented across the board, storing title ID's and title names
- Implemented a button to list installed ID's, and show updated ID's
- Implemented a delete confirmation message (app checks that the user is sure they wish to delete cheats, prior to deletion)
- Implemented a button to return to the main menu when finished with one task
- Majority of code that I have used has been commented and explained as best as I can.

### CODE REVIEW

**Comment by HamletDuFromage** [comment]
Hey sorry, I've been busy with class so I haven't had time to check it out. From what you wrote, it sounds neat! Hopefully by this weekend it will be merged

Thanks!

**Comment by wilsam239** [comment]
No worries! I'm also working on implementing a GUI for it, it's a bit slow going though, it's a public repo on my profile if you wanted to check it out.

Cheers!

**Comment by HamletDuFromage** [comment]
Tell me about it lmao, I've tried my hand at GUIs but gave up. That being said, as you probably realized by looking at my code, I'm not John Carmack. Excited to see how it turns out :)

**Comment by wilsam239** [comment]
Good thing you aren't, otherwise I'd have nothing to contribute I reckon!

I'm using Xor's Plutonium framework, and have a basic setup going at the moment, making the menu items do something instead of just stub functions will be the hard part I think


I'll keep you posted anyway!

**Comment by wilsam239** [comment]
Have you got a discord account/server mate?

**Comment by HamletDuFromage** [comment]
@simple#8155

**Pull request merged**
